### ISSUE TITLE
Duplicated diagnostic causing crash on DefaultDiagnosticConsoleFormatter

### ISSUE THREAD

**Issue by Kyle-Ye** [apple/swift-docc#729]
### Description

See detail on https://github.com/apple/swift-docc/issues/678#issuecomment-1748170163

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/apple/swift-docc/issues).

### Expected Behavior

Only emit one diagnostic for the actual location - the Extension file.

### Actual behavior

Emit 2 duplicated diagnostic: the Extension Markdown file and the source Swift file

### Steps To Reproduce

Change `eat(_:quantity:)` to `eat(_:quantity:extraLog:)` and build documentation for SlothCreator.

### Swift-DocC Version Information

5.9.0

### Swift Compiler Version Information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

**Comment by d-ronnqvist** [comment]
I think that I have looked into this in the past, before it resulted in a crash. Internally we're tracking this issue as rdar://79991171. I'll associate that radar with this issue so that people who find the radar can find this issue instead.

I may have some old notes that may still be relevant. Let me see if I can find them.

**Comment by d-ronnqvist** [comment]
I couldn't find my old notes but I vaguely remember that I got this far... 

It looks like the links is resolved [for the full content][1] but [for both "chunks"][2] (the in-source doc comment and the extensions code). 

We need to process both chunks so that we can get diagnostics to the right places but I think that the `ReferenceResolver` shouldn't visit the full semantic both times. 

I remember trying to change this and that it wasn't as easy as I thought but I don't remember what issues I encountered. 

[1]: https://github.com/apple/swift-docc/blob/main/Sources/SwiftDocC/Infrastructure/DocumentationContext.swift#L612
[2]: https://github.com/apple/swift-docc/blob/main/Sources/SwiftDocC/Infrastructure/DocumentationContext.swift#L572

**Comment by Kyle-Ye** [comment]
Can we filter such duplicated diagnostic by checking the source url matching? Here is my draft PR #733

Before the PR:

Emit 2 duplicated diagnostic: the Extension Markdown file and the source Swift file

And then crash on DefaultDiagnosticConsoleFormatter

After the PR:

```
[1;33mwarning: 'eat(_:quantity:)' doesn't exist at '/SlothCreator/Sloth'[0;0m
  --> Extensions/Sloth.md:12:5-12:21
10 | ### Engaging in Activities
11 | 
12 + - ``[1;32meat(_:quantity:)[0;0m``
   |     ╰─[1;39msuggestion: Replace 'eat(_:quantity:)' with 'eat(_:quantity:extraLog:)'[0;0m
13 | - ``sleep(in:for:)``
14 | ========================================
Starting Local Preview Server
	 Address: http://localhost:8080/documentation/slothcreator
	          http://localhost:8080/tutorials/slothcreator
```

If you agree on this general idea of the PR, I'll continue to work on it to add the test case. @d-ronnqvist

**Comment by d-ronnqvist** [comment]
That's sounds like a good idea.

**Comment by Kyle-Ye** [comment]
The test case is added and the PR is ready for a review. @d-ronnqvist

**Comment by Kyle-Ye** [comment]
This issue is not fully resolved. Encounter same crash recently.

> Background:
> https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/3061#issuecomment-2118872836

I can reproduce the issue on both release/5.10 and main using the large repo code.

But when I try to prepare a minimal reproducible package. It only crash for Xcode 15.3 or release/5.10 branch of swift-docc not on main branch.

I guess we have fixed part of the issue again on some commits on main branch.

I'll work on preparing a crash example case which will also crash on main branch of swift-docc later this week.

**Comment by Kyle-Ye** [comment]
A reproducible package

[DemoKit.zip](https://github.com/apple/swift-docc/files/15367633/DemoKit.zip)

```
swift package generate-documentation --verbose
# Copy `docc invocation` command and use the parameter to debug docc
```

It is still due to duplicated diagnostic problem (Emit the same issue in Demo.swift and Demo.md file)

**Comment by Kyle-Ye** [comment]
A quick fix for this issue is add [similar logic](#733) to the following position or `unresolvedResourceProblem`. See #918

https://github.com/apple/swift-docc/blob/5029117adab75c36f75e3a90fe4e691969730c84/Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift#L102-L105

But it feels like this does not seem to be the right direction, we just enumerate the holes. Similar crashes are still possible in the future. cc @d-ronnqvist

**Comment by d-ronnqvist** [comment]
> A quick fix for this issue is add [similar logic](#733) to the following position or `unresolvedResourceProblem`. See #918
> 
> https://github.com/apple/swift-docc/blob/5029117adab75c36f75e3a90fe4e691969730c84/Sources/SwiftDocC/Semantics/MarkupReferenceResolver.swift#L102-L105
> 
> But it feels like this does not seem to be the right direction, we just enumerate the holes. Similar crashes are still possible in the future. cc @d-ronnqvist

I agree that fixing individual places that create out-of-bounds diagnostic ranges doesn't address the root cause. 

As a first step to a long term fix we should make sure that the diagnostic formatter handles all out-of-bounds diagnostic ranges instead of assuming that they're valid. I opened #947 to do this. 

After that, @patshaughnessy and I talked about possible changes to design away the need to do two MarkupReferenceResolver passes. If those ideas pan out it will remove these duplicate diagnostics.
